// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using qlsinhvien.Data;

#nullable disable

namespace QuanLyySinhVien.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422033704_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("qlsinhvien.Models.DangKyHoc", b =>
                {
                    b.Property<int>("MaDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaDangKy"));

                    b.Property<int>("MaLopHocPhan")
                        .HasColumnType("int");

                    b.Property<int>("MaSinhVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("DangKy");

                    b.HasKey("MaDangKy");

                    b.HasIndex("MaLopHocPhan");

                    b.HasIndex("MaSinhVien", "MaLopHocPhan")
                        .IsUnique();

                    b.ToTable("DangKyHoc", (string)null);
                });

            modelBuilder.Entity("qlsinhvien.Models.HocKy", b =>
                {
                    b.Property<int>("MaHocKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaHocKy"));

                    b.Property<string>("NamHoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TenHocKy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.HasKey("MaHocKy");

                    b.HasIndex("TenHocKy", "NamHoc")
                        .IsUnique();

                    b.ToTable("HocKy", (string)null);
                });

            modelBuilder.Entity("qlsinhvien.Models.KetQuaHocTap", b =>
                {
                    b.Property<int>("MaKetQua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaKetQua"));

                    b.Property<decimal?>("DiemChuyenCan")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal?>("DiemCuoiKy")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal?>("DiemGiuaKy")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal?>("DiemKetThucHocPhan")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal?>("DiemQuaTrinh")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal?>("DiemTongKet")
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("KetQua")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("MaLopHocPhan")
                        .HasColumnType("int");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.HasKey("MaKetQua");

                    b.HasIndex("MaLopHocPhan");

                    b.HasIndex("MaTaiKhoan", "MaLopHocPhan")
                        .IsUnique();

                    b.ToTable("KetQuaHocTap", (string)null);
                });

            modelBuilder.Entity("qlsinhvien.Models.LopHoc", b =>
                {
                    b.Property<int>("MaLop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaLop"));

                    b.Property<string>("Khoa")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("MaNganh")
                        .HasColumnType("int");

                    b.Property<string>("NienKhoa")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaLop");

                    b.HasIndex("MaNganh");

                    b.HasIndex("TenLop")
                        .IsUnique();

                    b.ToTable("LopHoc", (string)null);
                });

            modelBuilder.Entity("qlsinhvien.Models.LopHocPhan", b =>
                {
                    b.Property<int>("MaLopHocPhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaLopHocPhan"));

                    b.Property<int>("MaGiangVien")
                        .HasColumnType("int");

                    b.Property<int>("MaHocKy")
                        .HasColumnType("int");

                    b.Property<int>("MaMonHoc")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongToiDa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(50);

                    b.Property<string>("TenLopHocPhan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ThoiGianBatDau")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ThoiGianKetThuc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("DangMo");

                    b.HasKey("MaLopHocPhan");

                    b.HasIndex("MaGiangVien");

                    b.HasIndex("MaHocKy");

                    b.HasIndex("MaMonHoc");

                    b.ToTable("LopHocPhan", (string)null);
                });

            modelBuilder.Entity("qlsinhvien.Models.MaKhoa", b =>
                {
                    b.Property<int>("Khoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Khoa"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Khoa");

                    b.HasIndex("TenKhoa")
                        .IsUnique();

                    b.ToTable("MaKhoa", (string)null);
                });

            modelBuilder.Entity("qlsinhvien.Models.MonHoc", b =>
                {
                    b.Property<int>("MaMonHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaMonHoc"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SoTinChi")
                        .HasColumnType("int");

                    b.Property<string>("TenMonHoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("MaMonHoc");

                    b.HasIndex("TenMonHoc")
                        .IsUnique();

                    b.ToTable("MonHoc", (string)null);
                });

            modelBuilder.Entity("qlsinhvien.Models.NganhHoc", b =>
                {
                    b.Property<int>("MaNganh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaNganh"));

                    b.Property<int>("MaKhoa")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("TenNganh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("MaNganh");

                    b.HasIndex("MaKhoa");

                    b.HasIndex("TenNganh", "MaKhoa")
                        .IsUnique();

                    b.ToTable("NganhHoc", (string)null);
                });

            modelBuilder.Entity("qlsinhvien.Models.PhanCongGiangDay", b =>
                {
                    b.Property<int>("MaPhanCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaPhanCong"));

                    b.Property<int>("MaGiangVien")
                        .HasColumnType("int");

                    b.Property<int>("MaHocKy")
                        .HasColumnType("int");

                    b.Property<int>("MaLop")
                        .HasColumnType("int");

                    b.Property<int>("MaMonHoc")
                        .HasColumnType("int");

                    b.HasKey("MaPhanCong");

                    b.HasIndex("MaHocKy");

                    b.HasIndex("MaLop");

                    b.HasIndex("MaMonHoc");

                    b.HasIndex("MaGiangVien", "MaMonHoc", "MaLop", "MaHocKy")
                        .IsUnique();

                    b.ToTable("PhanCongGiangDay", (string)null);
                });

            modelBuilder.Entity("qlsinhvien.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("ChuyenNganh")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("GioiTinh")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HocVi")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("MaLop")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MaLop");

                    b.HasIndex("SoDienThoai")
                        .IsUnique();

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("qlsinhvien.Models.DangKyHoc", b =>
                {
                    b.HasOne("qlsinhvien.Models.LopHocPhan", "LopHocPhan")
                        .WithMany("DangKyHocs")
                        .HasForeignKey("MaLopHocPhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("qlsinhvien.Models.TaiKhoan", "SinhVien")
                        .WithMany("DangKyHocs")
                        .HasForeignKey("MaSinhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHocPhan");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("qlsinhvien.Models.KetQuaHocTap", b =>
                {
                    b.HasOne("qlsinhvien.Models.LopHocPhan", "LopHocPhan")
                        .WithMany("KetQuaHocTaps")
                        .HasForeignKey("MaLopHocPhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("qlsinhvien.Models.TaiKhoan", "TaiKhoan")
                        .WithMany("KetQuaHocTaps")
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHocPhan");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("qlsinhvien.Models.LopHoc", b =>
                {
                    b.HasOne("qlsinhvien.Models.NganhHoc", "NganhHoc")
                        .WithMany("LopHocs")
                        .HasForeignKey("MaNganh")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NganhHoc");
                });

            modelBuilder.Entity("qlsinhvien.Models.LopHocPhan", b =>
                {
                    b.HasOne("qlsinhvien.Models.TaiKhoan", "GiangVien")
                        .WithMany("LopHocPhanGiangViens")
                        .HasForeignKey("MaGiangVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("qlsinhvien.Models.HocKy", "HocKy")
                        .WithMany("LopHocPhans")
                        .HasForeignKey("MaHocKy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("qlsinhvien.Models.MonHoc", "MonHoc")
                        .WithMany("LopHocPhans")
                        .HasForeignKey("MaMonHoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("HocKy");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("qlsinhvien.Models.NganhHoc", b =>
                {
                    b.HasOne("qlsinhvien.Models.MaKhoa", "KhoaInfo")
                        .WithMany("NganhHocs")
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhoaInfo");
                });

            modelBuilder.Entity("qlsinhvien.Models.PhanCongGiangDay", b =>
                {
                    b.HasOne("qlsinhvien.Models.TaiKhoan", "GiangVien")
                        .WithMany("PhanCongGiangDays")
                        .HasForeignKey("MaGiangVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("qlsinhvien.Models.HocKy", "HocKy")
                        .WithMany("PhanCongGiangDays")
                        .HasForeignKey("MaHocKy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("qlsinhvien.Models.LopHoc", "LopHoc")
                        .WithMany("PhanCongGiangDays")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("qlsinhvien.Models.MonHoc", "MonHoc")
                        .WithMany("PhanCongGiangDays")
                        .HasForeignKey("MaMonHoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("HocKy");

                    b.Navigation("LopHoc");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("qlsinhvien.Models.TaiKhoan", b =>
                {
                    b.HasOne("qlsinhvien.Models.LopHoc", "LopHoc")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("qlsinhvien.Models.HocKy", b =>
                {
                    b.Navigation("LopHocPhans");

                    b.Navigation("PhanCongGiangDays");
                });

            modelBuilder.Entity("qlsinhvien.Models.LopHoc", b =>
                {
                    b.Navigation("PhanCongGiangDays");

                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("qlsinhvien.Models.LopHocPhan", b =>
                {
                    b.Navigation("DangKyHocs");

                    b.Navigation("KetQuaHocTaps");
                });

            modelBuilder.Entity("qlsinhvien.Models.MaKhoa", b =>
                {
                    b.Navigation("NganhHocs");
                });

            modelBuilder.Entity("qlsinhvien.Models.MonHoc", b =>
                {
                    b.Navigation("LopHocPhans");

                    b.Navigation("PhanCongGiangDays");
                });

            modelBuilder.Entity("qlsinhvien.Models.NganhHoc", b =>
                {
                    b.Navigation("LopHocs");
                });

            modelBuilder.Entity("qlsinhvien.Models.TaiKhoan", b =>
                {
                    b.Navigation("DangKyHocs");

                    b.Navigation("KetQuaHocTaps");

                    b.Navigation("LopHocPhanGiangViens");

                    b.Navigation("PhanCongGiangDays");
                });
#pragma warning restore 612, 618
        }
    }
}
